# Generated by Django 3.2 on 2021-05-05 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('med_name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='medication name')),
                ('med_dose', models.CharField(max_length=15, verbose_name='dosage')),
                ('med_freq', models.CharField(max_length=15, verbose_name='frequency')),
                ('med_route', models.CharField(max_length=25, verbose_name='route')),
                ('med_timing', models.TimeField(verbose_name='timing')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('reminder_note', models.CharField(max_length=255)),
                ('med_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medreminderapp.medication')),
            ],
        ),
    ]
