# Generated by Django 3.2 on 2021-05-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medreminderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='med_dose',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='medication',
            name='med_freq',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='medication',
            name='med_name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='med_route',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='medication',
            name='med_timing',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_time',
            field=models.CharField(max_length=25),
        ),
    ]
